ApiBundle\Entity\UserGroup:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: ['user','user_group']
        name:
            expose: true
            groups: ['user_group']
        users:
            expose: true
            groups: ['user_group']
