# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.redis:
        class: Redis
        calls:
            - [connect, ["%redis.host%", "%redis.port%"]]
            - [select, ["%redis.db_number%"]]

    app.redis.adapter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments: ["@app.redis"]

    app.cache:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments: ["@app.redis.adapter","@app.redis.adapter"]
