version: '2'

services:
    db:
        image: mysql
        volumes:
            - ./.data/db:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:rw
            - ./logs/symfony:/var/www/symfony/app/logs:rw
    nginx:
        build: nginx
        ports:
            - 8042:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    redis:
        image: redis
        ports:
            - "6379"
