api_users:
    type: rest
    prefix: /v1/users
    resource: "@ApiBundle/Controller/UserController.php"
api_user_groups:
    type: rest
    prefix: /v1/groups
    resource: "@ApiBundle/Controller/GroupController.php"
