<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\Query;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandomGroups($count = 1, $hydration = Query::HYDRATE_OBJECT)
    {
        $totalRowsTable = $this->createQueryBuilder('g')->select('count(g.id)')->getQuery()->getSingleScalarResult();
        return $this->createQueryBuilder('g')
            ->select('g')
            ->setMaxResults($count)
            ->setFirstResult(rand(0, $totalRowsTable - $count - 1))
            ->getQuery()
            ->getResult($hydration);
    }
}
